name: lime_locator
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  bloc: ^8.1.2
  dio: ^5.4.0
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter

  freezed_annotation: ^2.4.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  shimmer: ^3.0.0
  timeago: ^3.6.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/json/

  fonts:
    - family: SplineSans
      fonts:
        - asset: "assets/fonts/SplineSans-Light.ttf"
          weight: 300
        - asset: "assets/fonts/SplineSans-Regular.ttf"
          weight: 400
        - asset: "assets/fonts/SplineSans-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/SplineSans-SemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/SplineSans-Bold.ttf"
          weight: 700
